"""add reg_number and program to users

Revision ID: 345959fabbb6
Revises: 0a00c93d681a
Create Date: 2025-09-03 15:49:15.254302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345959fabbb6'
down_revision = '0a00c93d681a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=False))

    with op.batch_alter_table('missing_mark_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('proof_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('lecturer_note', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'assessments', ['assessment_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('program', sa.String(length=160), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_reg_number'), ['reg_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reg_number'))
        batch_op.drop_column('program')
        batch_op.drop_column('reg_number')

    with op.batch_alter_table('missing_mark_reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lecturer_note')
        batch_op.drop_column('status')
        batch_op.drop_column('proof_url')
        batch_op.drop_column('message')
        batch_op.drop_column('assessment_id')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('is_published')
        batch_op.drop_column('due_at')

    # ### end Alembic commands ###
