"""Add study_mode to assessments

Revision ID: 5991e46eb979
Revises: 0666f12b90da
Create Date: 2025-10-11 17:05:55.176377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5991e46eb979'
down_revision = '0666f12b90da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_mode', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessments_study_mode'), ['study_mode'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_id'), ['school_id'], unique=False)
        batch_op.create_foreign_key('fk_users_program_id', 'programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_users_school_id', 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_school_id', type_='foreignkey')
        batch_op.drop_constraint('fk_users_program_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_school_id'))
        batch_op.drop_index(batch_op.f('ix_users_program_id'))

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_study_mode'))
        batch_op.drop_column('study_mode')

    # ### end Alembic commands ###
