"""Add school and program fields to departments

Revision ID: ec3ca53d7961
Revises: 5991e46eb979
Create Date: 2025-10-12 08:58:15.370383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3ca53d7961'
down_revision = '5991e46eb979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('program_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_type', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_departments_department_type'), ['department_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_school_id'), ['school_id'], unique=False)
        batch_op.create_foreign_key('fk_departments_program_id', 'programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_departments_school_id', 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_id'), ['school_id'], unique=False)
        batch_op.create_foreign_key('fk_users_program_id', 'programs', ['program_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_users_school_id', 'schools', ['school_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_school_id', type_='foreignkey')
        batch_op.drop_constraint('fk_users_program_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_school_id'))
        batch_op.drop_index(batch_op.f('ix_users_program_id'))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_departments_school_id', type_='foreignkey')
        batch_op.drop_constraint('fk_departments_program_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_departments_school_id'))
        batch_op.drop_index(batch_op.f('ix_departments_program_id'))
        batch_op.drop_index(batch_op.f('ix_departments_department_type'))
        batch_op.drop_column('department_type')
        batch_op.drop_column('program_id')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
